services:
  app:
    image: myaspnetapp
    build:
      context: .
      dockerfile: AutodorInfoSystem/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    env_file:
      - path: ./environment/default.env
        required: true
    networks:
      - backend

  db:
    image: mysql:9.1
    env_file:
      - path: ./environment/mysql.env
        required: true
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    external: false
    driver: bridge