services:
  app:
    image: myaspnetapp
    build:
      context: .
      dockerfile: AutodorInfoSystem/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - MySQLConnString=${MySQLConnString}
      - JWTKey={JWTKey}
      - JWTIssuer={JWTIssuer}
      - JWTAudience={JWTAudience}

  db:
    image: mysql:9.1
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"